dependencies:
- name: exposecontroller
  version: 2.3.89
  repository: http://chartmuseum.jenkins-x.io
  alias: expose
- name: exposecontroller
  version: 2.3.89
  repository: http://chartmuseum.jenkins-x.io
  alias: cleanup
- name: mavenqs
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: pa-emailchat
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.18
- name: pa-emailparser
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: pa-nattydate
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.10
- name: pa-recurrent-nattydatetime
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.8
- name: pa-scheduler-kue-rediscluster
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.29
